// The API has no time zone for circuits, so map the ones on recent calendars.
const CIRCUIT_TIMEZONES: Record<string, string> = {
  albert_park: "Australia/Melbourne",
  shanghai: "Asia/Shanghai",
  suzuka: "Asia/Tokyo",
  bahrain: "Asia/Bahrain",
  jeddah: "Asia/Riyadh",
  miami: "America/New_York",
  imola: "Europe/Rome",
  monaco: "Europe/Monaco",
  villeneuve: "America/Toronto",
  catalunya: "Europe/Madrid",
  madring: "Europe/Madrid",
  red_bull_ring: "Europe/Vienna",
  silverstone: "Europe/London",
  spa: "Europe/Brussels",
  hungaroring: "Europe/Budapest",
  zandvoort: "Europe/Amsterdam",
  monza: "Europe/Rome",
  baku: "Asia/Baku",
  marina_bay: "Asia/Singapore",
  americas: "America/Chicago",
  rodriguez: "America/Mexico_City",
  interlagos: "America/Sao_Paulo",
  vegas: "America/Los_Angeles",
  losail: "Asia/Qatar",
  yas_marina: "Asia/Dubai",
  portimao: "Europe/Lisbon",
  istanbul: "Europe/Istanbul",
  sochi: "Europe/Moscow",
  ricard: "Europe/Paris",
  nurburgring: "Europe/Berlin",
  hockenheimring: "Europe/Berlin",
  mugello: "Europe/Rome",
  sepang: "Asia/Kuala_Lumpur",
  yeongam: "Asia/Seoul",
  buddh: "Asia/Kolkata",
};

export const getCircuitTimezone = (circuitId: string) =>
  CIRCUIT_TIMEZONES[circuitId];
